#include "test.hpp"
#include "surreal/causal.hpp"
#include "surreal/entropy.hpp"
#include "surreal/horizon.hpp"
#include "surreal/physics.hpp"
#include "surreal/rewrite.hpp"
#include "surreal/universe.hpp"
#include "surreal/units.hpp"
#include <filesystem>
#include <string>
#include <unistd.h>
using namespace std::string_literals;

static surreal::InvariantCertificate ok(){surreal::InvariantCertificate c;c.pass=true;c.claims["ok"]="1";return c;}
int main(){using namespace surreal;
  CausalGraph g;Event a;a.local_time=Rational(0);a.region="r";a.law="a";a.before_hash="b";a.after_hash="c";a.invariant_hash="i";a.entropy_root="e";auto aid=g.append(a);Event b=a;b.parents={aid};b.local_time=Rational(1);b.law="b";auto bid=g.append(b);CHECK(g.at(bid).depth==1);CHECK_THROWS(([&]{Event x=a;x.parents={"missing"};g.append(x);}()));CHECK_THROWS(([&]{Event x=a;x.parents={bid};x.local_time=Rational(0);g.append(x);}()));CHECK_EQ(causal_boundary_root(g,{aid,bid,bid}),causal_boundary_root(g,{bid,aid}));

  Universe u(7);u.declare_law("test.transition");CHECK(u.law_declared("test.transition"));CHECK(!u.law_declared("not.declared"));u.put_region({"r","demo","A"});CHECK_THROWS(u.put_region({"r","demo","duplicate"}));CHECK_THROWS(u.transition("r","undeclared",Rational(0),{},"p",true,[](const std::string&){return std::pair<std::string,InvariantCertificate>{"X",ok()};}));auto root=u.transition("r","test.transition",Rational(0),{},"p",true,[](const std::string&){return std::pair<std::string,InvariantCertificate>{"B",ok()};});Universe common=u.fork();CHECK(common.region_identity("r")==u.region_identity("r"));CHECK_EQ(common.entropy().draw(),u.entropy().draw());Universe p(7);p.put_region({"r","demo","A"});auto independent=p.fork_independent("branch-B");auto independent2=p.fork_independent("branch-B");CHECK_EQ(independent.entropy().stream_id(),independent2.entropy().stream_id());CHECK(independent.entropy().draw()!=p.entropy().draw());Universe live;CHECK_THROWS(live.fork_independent("branch"));common.perturb_region("r","C");CHECK(common.region_identity("r")!=u.region_identity("r"));CHECK_EQ(common.invalidated_future(root).size(),std::size_t(0));

  Universe tx(11);tx.declare_law("test.entropy");tx.declare_law("test.deterministic");tx.put_region({"r","demo","A"});auto counter_before=tx.entropy().counter();auto root_before=tx.entropy().root();CHECK_THROWS(tx.transition("r","test.entropy",Rational(0),{},"p",false,[&](const std::string&){(void)tx.entropy().draw();InvariantCertificate fail;fail.pass=false;return std::pair<std::string,InvariantCertificate>{"B",fail};}));CHECK_EQ(tx.entropy().counter(),counter_before);CHECK_EQ(tx.entropy().root(),root_before);CHECK_EQ(tx.region("r").payload,std::string("A"));CHECK_THROWS(tx.transition("r","test.deterministic",Rational(0),{},"p",true,[&](const std::string&){(void)tx.entropy().draw();return std::pair<std::string,InvariantCertificate>{"B",ok()};}));CHECK_EQ(tx.entropy().counter(),counter_before);CHECK_EQ(tx.entropy().root(),root_before);CHECK_EQ(tx.region("r").payload,std::string("A"));

  Universe atomic(17);atomic.declare_law("test.atomic");atomic.put_region({"r","demo","A"});auto first=atomic.transition("r","test.atomic",Rational(1),{},"same",true,[](const std::string&){return std::pair<std::string,InvariantCertificate>{"B",ok()};});atomic.perturb_region("r","A");(void)atomic.transition("r","test.atomic",Rational(1),{},"same",true,[](const std::string&){return std::pair<std::string,InvariantCertificate>{"B",ok()};});atomic.perturb_region("r","A");const auto graph_before=atomic.causal().size();CHECK_THROWS(atomic.transition("r","test.atomic",Rational(1),{},"same",true,[](const std::string&){return std::pair<std::string,InvariantCertificate>{"B",ok()};}));CHECK_EQ(atomic.region("r").payload,std::string("A"));CHECK_EQ(atomic.causal().size(),graph_before);int called=0;CHECK_THROWS(atomic.transition("r","test.atomic",Rational(0),{first},"late",true,[&](const std::string&){++called;return std::pair<std::string,InvariantCertificate>{"C",ok()};}));CHECK(called==0);CHECK_EQ(atomic.region("r").payload,std::string("A"));CHECK_EQ(atomic.causal().size(),graph_before);CHECK_THROWS(atomic.put_region({"bad\nid","demo","x"}));

  EntropyLedger audit(123);(void)audit.draw();(void)audit.draw();auto log=audit.audit_log();std::string entropy_error;CHECK(verify_entropy_log(log,audit.root(),&entropy_error));auto corrupt=log;auto dp=corrupt.find("draw=0:");CHECK(dp!=std::string::npos);if(dp!=std::string::npos){auto n=corrupt.find_first_of("0123456789",dp+7);CHECK(n!=std::string::npos);if(n!=std::string::npos)corrupt[n]=(corrupt[n]=='9'?'8':'9');}CHECK(!verify_entropy_log(corrupt,audit.root(),&entropy_error));

  Universe m(9);m.declare_law("test.inc");m.put_region({"x","memo","0"});int calls=0;auto e0=m.transition("x","test.inc",Rational(0),{},"same",true,[&](const std::string&){++calls;return std::pair<std::string,InvariantCertificate>{"1",ok()};});m.perturb_region("x","0");auto e1=m.transition("x","test.inc",Rational(1),{},"same",true,[&](const std::string&){++calls;return std::pair<std::string,InvariantCertificate>{"1",ok()};});CHECK(calls==1);CHECK(m.causal().at(e1).memo_reuse);(void)e0;

  BodySystem bs;bs.bodies={{"a",Rational(2),Rational(1),{Interval(Rational(-1)),Interval(Rational(0)),Interval(Rational(0))},{Interval(Rational(0)),Interval(Rational(1)),Interval(Rational(0))}},{"b",Rational(2),Rational(-1),{Interval(Rational(1)),Interval(Rational(0)),Interval(Rational(0))},{Interval(Rational(0)),Interval(Rational(-1)),Interval(Rational(0))}}};auto gr=gravity_kdk(bs,Rational(1,BigInt(100)),Rational(1),Rational(1,BigInt(100)));CHECK(gr.invariant.pass);auto cr=coulomb_kick(bs,Rational(1,BigInt(100)),Rational(1),Rational(1,BigInt(100)));CHECK(cr.invariant.pass);
  EntropyLedger el(123);auto dr=stochastic_two_body_decay(bs,0,Rational(1),el);CHECK(dr.invariant.pass&&dr.state.bodies.size()==3);auto rr=rest_mass_to_radiation(bs,0,Rational(1,BigInt(2)));CHECK(rr.invariant.pass);Body photon{"ph",Rational(0),Rational(0),{Interval(Rational(0)),Interval(Rational(0)),Interval(Rational(0))},{Interval(Rational(0)),Interval(Rational(0)),Interval(Rational(0))}};Vec3I dir{Interval(Rational(1)),Interval(Rational(0)),Interval(Rational(0))};CHECK(photon_propagate(photon,dir,Rational(3)).position.x.contains(Rational(3)));
  CosmologyState cs{Interval(Rational(1)),"lcdm"};CHECK(friedmann_step(cs,Rational(1,BigInt(100))).scale_factor.lo>Rational(1));CHECK_THROWS(cosmology_world("made-up"));CHECK(law_catalogue_json_lines().size()>=9);CHECK(formula_catalogue_json_lines().size()>=15);

  LawProgram lp{{{OpCode::LoadX,Rational(0)},{OpCode::PushConst,Rational(0)},{OpCode::Add,Rational(0)},{OpCode::PushConst,Rational(1)},{OpCode::Mul,Rational(0)}}};auto fr=self_rewrite_kernel(lp,{Rational(-1),Rational(0),Rational(2)});CHECK(fr.program.code.size()==1);CHECK(verify_rewrite_certificate(lp,fr.program,fr.certificate));auto bad=fr.certificate;bad.steps[0].after_hash[0]=bad.steps[0].after_hash[0]=='0'?'1':'0';CHECK(!verify_rewrite_certificate(lp,fr.program,bad));auto huge=fr.certificate;huge.steps.resize(kMaxRewriteSteps+1);CHECK(!verify_rewrite_certificate(lp,fr.program,huge));

  auto td=std::filesystem::temp_directory_path()/("surreal_horizon_test_"+std::to_string(::getpid()));std::filesystem::remove_all(td);std::filesystem::create_directories(td);RegionState hr{"r\nencoded","k=encoded","payload\nkind=evil\0tail"s};auto sealed=seal_horizon(hr,g.root_hash(),(td/"horizon.dat").string());auto opened=reopen_horizon((td/"horizon.dat").string());CHECK_EQ(opened.commitment,sealed.commitment);CHECK_EQ(opened.region.id,hr.id);CHECK_EQ(opened.region.kind,hr.kind);CHECK_EQ(opened.region.payload,hr.payload);auto anchored=reopen_horizon_anchored((td/"horizon.dat").string(),sealed.commitment);CHECK_EQ(anchored.region.payload,hr.payload);CHECK_THROWS(reopen_horizon_anchored((td/"horizon.dat").string(),std::string(64,'0')));std::filesystem::remove_all(td);
  return finish_tests();}
