#include "surreal/exact.hpp"
#include <algorithm>
#include <sstream>
#include <stdexcept>
#include <vector>

namespace surreal {
namespace {
BigInt abs_big(BigInt x){ return x<0?-x:x; }
BigInt gcd_big(BigInt a, BigInt b){ a=abs_big(a); b=abs_big(b); while(b!=0){ BigInt r=a%b;a=b;b=r;} return a; }
BigInt pow10(unsigned n){ BigInt x=1; for(unsigned i=0;i<n;++i)x*=10; return x; }
BigInt isqrt_floor(const BigInt& n){ if(n<0) throw std::domain_error("sqrt negative integer"); if(n<2) return n; unsigned bits=boost::multiprecision::msb(n)+1; BigInt x=BigInt(1)<<((bits+1)/2); for(;;){ BigInt y=(x+n/x)/2; if(y>=x) return x; x=y; } }
}
Rational::Rational():n_(0),d_(1){}
Rational::Rational(long long n):n_(n),d_(1){}
Rational::Rational(BigInt n, BigInt d):n_(std::move(n)),d_(std::move(d)){normalize();}
void Rational::normalize(){ if(d_==0) throw std::domain_error("zero denominator"); if(d_<0){n_=-n_;d_=-d_;} if(n_==0){d_=1;return;} auto g=gcd_big(n_,d_);n_/=g;d_/=g; }
Rational Rational::parse(std::string_view s){ auto slash=s.find('/'); try { if(slash==std::string_view::npos) return Rational(BigInt(std::string(s)),1); return Rational(BigInt(std::string(s.substr(0,slash))),BigInt(std::string(s.substr(slash+1)))); } catch(...) { throw std::invalid_argument("invalid rational"); } }
std::string Rational::str() const { if(d_==1)return n_.convert_to<std::string>(); return n_.convert_to<std::string>()+"/"+d_.convert_to<std::string>(); }
Rational Rational::abs() const{return Rational(abs_big(n_),d_);} Rational Rational::reciprocal() const{if(n_==0)throw std::domain_error("reciprocal zero");return Rational(d_,n_);} Rational Rational::operator-() const{return Rational(-n_,d_);} 
Rational operator+(const Rational&a,const Rational&b){return Rational(a.n_*b.d_+b.n_*a.d_,a.d_*b.d_);} Rational operator-(const Rational&a,const Rational&b){return Rational(a.n_*b.d_-b.n_*a.d_,a.d_*b.d_);} Rational operator*(const Rational&a,const Rational&b){return Rational(a.n_*b.n_,a.d_*b.d_);} Rational operator/(const Rational&a,const Rational&b){if(b.n_==0)throw std::domain_error("divide by zero");return Rational(a.n_*b.d_,a.d_*b.n_);} 
std::strong_ordering operator<=>(const Rational&a,const Rational&b){BigInt l=a.n_*b.d_,r=b.n_*a.d_;if(l<r)return std::strong_ordering::less;if(l>r)return std::strong_ordering::greater;return std::strong_ordering::equal;}
Rational min(const Rational&a,const Rational&b){return a<b?a:b;} Rational max(const Rational&a,const Rational&b){return a>b?a:b;} Rational square(const Rational&a){return a*a;}
Interval::Interval():lo(0),hi(0){} Interval::Interval(Rational x):lo(x),hi(std::move(x)){} Interval::Interval(Rational l,Rational h):lo(std::move(l)),hi(std::move(h)){if(hi<lo)throw std::invalid_argument("interval order");}
std::string Interval::str()const{return "["+lo.str()+","+hi.str()+"]";} bool Interval::contains(const Rational&x)const{return lo<=x&&x<=hi;} bool Interval::contains_zero()const{return contains(Rational(0));} Interval Interval::operator-()const{return Interval(-hi,-lo);} 
Interval operator+(const Interval&a,const Interval&b){return Interval(a.lo+b.lo,a.hi+b.hi);} Interval operator-(const Interval&a,const Interval&b){return Interval(a.lo-b.hi,a.hi-b.lo);} 
Interval operator*(const Interval&a,const Interval&b){std::array<Rational,4> v={a.lo*b.lo,a.lo*b.hi,a.hi*b.lo,a.hi*b.hi};auto lo=*std::min_element(v.begin(),v.end());auto hi=*std::max_element(v.begin(),v.end());return Interval(lo,hi);} Interval operator/(const Interval&a,const Interval&b){if(b.contains_zero())throw std::domain_error("interval divide through zero"); Interval inv(b.hi.reciprocal(),b.lo.reciprocal()); if(inv.hi<inv.lo) inv=Interval(inv.hi,inv.lo); return a*inv;}
Interval square(const Interval&a){ if(a.contains_zero()) return Interval(Rational(0),max(square(a.lo),square(a.hi))); return Interval(min(square(a.lo),square(a.hi)),max(square(a.lo),square(a.hi))); }
Interval sqrt_interval(const Interval& x,unsigned digits){ if(x.lo<Rational(0)) throw std::domain_error("sqrt negative interval"); BigInt scale=pow10(digits); BigInt scale2=scale*scale; auto bound=[&](const Rational&r,bool upper){ BigInt N=r.num()*scale2; BigInt D=r.den(); BigInt q=N/D; if(N%D!=0 && upper) ++q; BigInt root=isqrt_floor(q); if(upper && root*root<q) ++root; return Rational(root,scale); }; return Interval(bound(x.lo,false),bound(x.hi,true)); }
Quadratic::Quadratic(Rational a_,Rational b_,BigInt d_):a(std::move(a_)),b(std::move(b_)),d(std::move(d_)){if(d<0)throw std::invalid_argument("negative radicand");}
std::string Quadratic::str()const{return a.str()+"+("+b.str()+")*sqrt("+d.convert_to<std::string>()+")";} Quadratic operator+(const Quadratic&x,const Quadratic&y){if(x.d!=y.d)throw std::invalid_argument("quadratic field mismatch");return Quadratic(x.a+y.a,x.b+y.b,x.d);} Quadratic operator-(const Quadratic&x,const Quadratic&y){if(x.d!=y.d)throw std::invalid_argument("quadratic field mismatch");return Quadratic(x.a-y.a,x.b-y.b,x.d);} Quadratic operator*(const Quadratic&x,const Quadratic&y){if(x.d!=y.d)throw std::invalid_argument("quadratic field mismatch");Rational dR(x.d,1);return Quadratic(x.a*y.a+x.b*y.b*dR,x.a*y.b+x.b*y.a,x.d);} Quadratic Quadratic::scale(const Rational&r)const{return Quadratic(a*r,b*r,d);}
SurrealScale::SurrealScale()=default; SurrealScale SurrealScale::constant(Rational c){SurrealScale s;s.set(0,std::move(c));return s;} SurrealScale SurrealScale::omega(){SurrealScale s;s.set(1,Rational(1));return s;} SurrealScale SurrealScale::infinitesimal(){SurrealScale s;s.set(-1,Rational(1));return s;} void SurrealScale::set(long long e,Rational c){if(c.is_zero())terms_.erase(e);else terms_[e]=std::move(c);} Rational SurrealScale::coefficient(long long e)const{auto it=terms_.find(e);return it==terms_.end()?Rational(0):it->second;} void SurrealScale::prune(){for(auto it=terms_.begin();it!=terms_.end();){if(it->second.is_zero())it=terms_.erase(it);else++it;}} std::string SurrealScale::str()const{if(terms_.empty())return "0";std::ostringstream o;bool first=true;for(auto&[e,c]:terms_){if(!first)o<<" + ";first=false;o<<c.str()<<"*omega^"<<e;}return o.str();} SurrealScale operator+(const SurrealScale&a,const SurrealScale&b){auto r=a;for(auto&[e,c]:b.terms_)r.set(e,r.coefficient(e)+c);return r;} SurrealScale operator*(const SurrealScale&a,const SurrealScale&b){SurrealScale r;for(auto&[ea,ca]:a.terms_)for(auto&[eb,cb]:b.terms_)r.set(ea+eb,r.coefficient(ea+eb)+ca*cb);return r;}
HahnSeries::HahnSeries()=default; HahnSeries HahnSeries::monomial(Rational e,Rational c){HahnSeries s;s.set(std::move(e),std::move(c));return s;} HahnSeries HahnSeries::one(){return monomial(Rational(0),Rational(1));} HahnSeries HahnSeries::omega(){return monomial(Rational(1),Rational(1));} HahnSeries HahnSeries::infinitesimal(){return monomial(Rational(-1),Rational(1));} void HahnSeries::set(Rational e,Rational c){if(c.is_zero())terms_.erase(e);else terms_[std::move(e)]=std::move(c);} Rational HahnSeries::coefficient(const Rational&e)const{auto it=terms_.find(e);return it==terms_.end()?Rational(0):it->second;} void HahnSeries::prune(){for(auto it=terms_.begin();it!=terms_.end();){if(it->second.is_zero())it=terms_.erase(it);else++it;}} std::string HahnSeries::str()const{if(terms_.empty())return "0";std::ostringstream o;bool first=true;for(auto&[e,c]:terms_){if(!first)o<<" + ";first=false;o<<c.str()<<"*omega^("<<e.str()<<")";}return o.str();} HahnSeries operator+(const HahnSeries&a,const HahnSeries&b){auto r=a;for(auto&[e,c]:b.terms_)r.set(e,r.coefficient(e)+c);return r;} HahnSeries operator*(const HahnSeries&a,const HahnSeries&b){HahnSeries r;for(auto&[ea,ca]:a.terms_)for(auto&[eb,cb]:b.terms_)r.set(ea+eb,r.coefficient(ea+eb)+ca*cb);return r;}
}
