#include "surreal/rewrite.hpp"
#include "surreal/hash.hpp"
#include "canonical_internal.hpp"
#include <stdexcept>

namespace surreal {
std::string Instruction::canonical()const{switch(op){case OpCode::PushConst:return "PUSH:"+value.str();case OpCode::LoadX:return "LOAD_X";case OpCode::Add:return "ADD";case OpCode::Mul:return "MUL";case OpCode::Dup:return "DUP";case OpCode::Swap:return "SWAP";}throw std::logic_error("opcode");}
std::string LawProgram::canonical()const{if(code.size()>kMaxLawInstructions)throw std::length_error("law program instruction bound");std::string s="SURREAL_LAW_VM_V2\n";detail::append_field(s,"instruction_count",std::to_string(code.size()));for(const auto&i:code)detail::append_field(s,"instruction",i.canonical());return s;}
std::string LawProgram::hash()const{return hex(sha256(canonical()));}
Rational LawProgram::evaluate(const Rational&x)const{if(code.size()>kMaxLawInstructions)throw std::length_error("law program instruction bound");std::vector<Rational> st;st.reserve(code.size());for(const auto&i:code){switch(i.op){case OpCode::PushConst:st.push_back(i.value);break;case OpCode::LoadX:st.push_back(x);break;case OpCode::Add:{if(st.size()<2)throw std::runtime_error("stack underflow");auto b=st.back();st.pop_back();auto a=st.back();st.back()=a+b;break;}case OpCode::Mul:{if(st.size()<2)throw std::runtime_error("stack underflow");auto b=st.back();st.pop_back();auto a=st.back();st.back()=a*b;break;}case OpCode::Dup:if(st.empty())throw std::runtime_error("stack underflow");st.push_back(st.back());break;case OpCode::Swap:if(st.size()<2)throw std::runtime_error("stack underflow");std::swap(st[st.size()-1],st[st.size()-2]);break;}if(st.size()>kMaxLawInstructions)throw std::length_error("law stack bound");}if(st.size()!=1)throw std::runtime_error("program result arity");return st.back();}
std::string RewriteCertificate::root()const{if(steps.size()>kMaxRewriteSteps)throw std::length_error("rewrite certificate step bound");std::string s="SURREAL_REWRITE_CERT_V2\n";detail::append_field(s,"original",original_hash);detail::append_field(s,"final",final_hash);detail::append_field(s,"step_count",std::to_string(steps.size()));for(const auto&x:steps){std::string t;detail::append_field(t,"rule",x.rule);detail::append_field(t,"index",std::to_string(x.index));detail::append_field(t,"before",x.before_hash);detail::append_field(t,"after",x.after_hash);detail::append_field(s,"step",t);}return hex(sha256(s));}
namespace {
bool apply_named(LawProgram&p,const std::string&rule,std::size_t i){if(i+1>=p.code.size())return false;if(rule=="add_zero"&&p.code[i].op==OpCode::PushConst&&p.code[i].value==Rational(0)&&p.code[i+1].op==OpCode::Add){p.code.erase(p.code.begin()+static_cast<std::ptrdiff_t>(i),p.code.begin()+static_cast<std::ptrdiff_t>(i+2));return true;}if(rule=="mul_one"&&p.code[i].op==OpCode::PushConst&&p.code[i].value==Rational(1)&&p.code[i+1].op==OpCode::Mul){p.code.erase(p.code.begin()+static_cast<std::ptrdiff_t>(i),p.code.begin()+static_cast<std::ptrdiff_t>(i+2));return true;}return false;}
bool one_rewrite(LawProgram&p,RewriteStep&step){for(std::size_t i=0;i+1<p.code.size();++i){for(const auto&rule:{std::string("add_zero"),std::string("mul_one")}){LawProgram q=p;if(apply_named(q,rule,i)){step={rule,i,p.hash(),q.hash()};p=std::move(q);return true;}}}return false;}
bool corpus_equal(const LawProgram&a,const LawProgram&b,const std::vector<Rational>&c){for(const auto&x:c)if(a.evaluate(x)!=b.evaluate(x))return false;return true;}
}
ForgeResult self_rewrite_kernel(const LawProgram&input,const std::vector<Rational>&corpus){if(corpus.empty())throw std::invalid_argument("empty rewrite corpus");if(corpus.size()>kMaxRewriteCorpus)throw std::length_error("rewrite corpus bound");if(input.code.size()>kMaxLawInstructions)throw std::length_error("law program instruction bound");ForgeResult r;r.program=input;r.certificate.original_hash=input.hash();r.lineage.push_back(input.hash());for(;;){if(r.certificate.steps.size()>=kMaxRewriteSteps)throw std::length_error("rewrite step bound");RewriteStep s;if(!one_rewrite(r.program,s))break;r.certificate.steps.push_back(s);r.lineage.push_back(r.program.hash());}r.certificate.final_hash=r.program.hash();if(!corpus_equal(input,r.program,corpus))throw std::runtime_error("rewrite semantic mismatch");if(r.program.code.size()>input.code.size())throw std::runtime_error("rewrite not structurally improved");if(!verify_rewrite_certificate(input,r.program,r.certificate))throw std::runtime_error("rewrite certificate self-check failed");return r;}
bool verify_rewrite_certificate(const LawProgram&original,const LawProgram&claimed,const RewriteCertificate&c){if(original.code.size()>kMaxLawInstructions||claimed.code.size()>kMaxLawInstructions||c.steps.size()>kMaxRewriteSteps)return false;if(c.original_hash!=original.hash()||c.final_hash!=claimed.hash())return false;LawProgram p=original;for(const auto&s:c.steps){if(p.hash()!=s.before_hash)return false;if(!apply_named(p,s.rule,s.index))return false;if(p.hash()!=s.after_hash)return false;}return p.hash()==claimed.hash();}
}  // namespace surreal
